buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        //the R8 version bundled with AGP 8.1.0+ causes crashes on very old Android versions

        //This affects ICS and Lollipop at least, maybe also KitKat
        classpath 'com.android.tools.build:gradle:8.12.0'
    }
}

allprojects {

    ext {
        appName = 'Rearranged Pixel Dungeon CN'
        appPackageName = 'com.rearrangedpixel.rearrangedpixeldungoncn'

        appVersionCode = 850
        appVersionName = '3.1.1'
        appVersionCode += 59
        appVersionName += '_based_3.37.0_cn'

        appJavaCompatibility = JavaVersion.VERSION_17  //1_8

        appAndroidCompileSDK = 35 //compile SDK is still 33 atm as we're sticking with AGP 8.0.2
        appAndroidMinSDK = 21
        appAndroidTargetSDK = 34

        gdxVersion = '1.12.1'
        gdxControllersVersion = '2.2.4-SNAPSHOT'
        robovmVersion = '2.3.20'
    }
    version = appVersionName

    repositories {
        google()
        mavenCentral()
        maven { url 'https://central.sonatype.com/repository/maven-snapshots/' }
    }
}